apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-worker
  namespace: trading
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: prefect-worker
  template:
    metadata:
      labels:
        app: prefect-worker
    spec:
      containers:
        - name: prefect-worker
          image: ghcr.io/choizeus02/personal-data-hub:163d3210c37c970822cd0ffdaac7fd532038c38a
          command: ["prefect", "worker", "start", "--pool", "personal-data-hub-pool"]
          envFrom:
            - secretRef:
                name: personal-data-hub-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
