apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-worker
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-worker
  template:
    metadata:
      labels:
        app: prefect-worker
    spec:
      containers:
        - name: prefect-worker
          image: ghcr.io/choizeus02/personal-data-hub:9851269177e6a9282a1bd0ec1ef37d1aa7dfbdd7
          command: ["prefect", "worker", "start", "--pool", "personal-data-hub-pool"]
          envFrom:
            - secretRef:
                name: personal-data-hub-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
